language: python
sudo: false
dist: trusty
cache:
  directories:
  - "$HOME/.cache/pip"
_install: &_install
  - gimme 1.8
  - source ~/.gimme/envs/latest.env
  - pip install --upgrade pip
  - pip install -r requirements.txt codecov
  - pip install -e index
_coverage: &_coverage
  - SCRIPT="coverage run -m unittest discover"
matrix:
  include:
    - python: 2.7
      env: *_coverage
      install: *_install
    # - python: 3.5
    #   env: *_coverage
    #   install: *_install
    # - python: 3.6
    #   env: *_coverage
    #   install: *_install
      after_success:
        - codecov
  fast_finish: true
script:
- (eval "$SCRIPT")
notifications:
  email: false