version: '3'
services:
  website:
    build: ./website
    ports:
     - "5000:5000"
    environment:
     - EMBEDDING_SERVICE_URL=http://nn_embeddings:5001
     - INDEX_SERVICE_URL=http://index:5002
    volumes:
     - ./data/img_celeba:/website/app/static/celeb_faces/
    tty: true
  nn_embeddings:
    build: ./nn_embeddings
    ports:
     - "5001:5001"
    volumes:
     - ./data:/nn_embeddings/data
  index:
    build: ./index
    ports:
     - "5002:5002"
    volumes:
     - ./data:/home/index/data